name: Deploy to github pages
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Build docs by vuepress
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install npm dependencies
        run: npm install
      - name: build docs
        run: npm run build
      - name: Upload vuepress build result
        uses: actions/upload-artifact@v2
        with:
          name: vuepress-dist
          path: dist
  deploy:
    name: Deploy to github pages
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - name: Download previous build result
        uses: actions/download-artifact@v3
        with:
          name: vuepress-dist
      - name: View artifact files
        run: ls
      - name: Deploy ðŸš€
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: . # The folder the action should deploy.
          CLEAN: true # Automatically remove deleted files from the deploy branch
